### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by nyatindopatrick** [nyatindopatrick/dinnear#3]
Please feel free to leave some comments and suggestions

**Comment by dili021** [comment]
A bit of overflow and overlap here 
![image](https://user-images.githubusercontent.com/55356496/75134463-afc6ef00-56de-11ea-891d-dacbb836047b.png)
Nice overlay and hover effect on the restaurant images.

Bottom button alignment
![image](https://user-images.githubusercontent.com/55356496/75134578-046a6a00-56df-11ea-84c9-278ec6e0a7e4.png)

Footer is looking great now.

H-scroll
![image](https://user-images.githubusercontent.com/55356496/75134662-42678e00-56df-11ea-9eb1-c7918cffcbfd.png)
.footer-list-one and the search button are causing it

Good work overall man!

**Comment by Kyle-Law** [comment]
Great Job @nyatindopatrick ! It's awesome that you applied the different navbar displays for different screen sizes. Here are my humble remarks:

- Not sure it's only happened to me or for others as well, images on the middle section seems to be overflowed for screen sizes above 769px.
![image](https://user-images.githubusercontent.com/55923773/75134567-aa3aca80-5719-11ea-8382-85141c81b49d.png)
- For the individual restaurant page, mobile size, maybe it'd look better to align the title into the center
![image](https://user-images.githubusercontent.com/55923773/75134655-e4a46780-5719-11ea-8640-9ed04bde3408.png)

That's all from me. It's awesome that you embedded maps into your individual restaurant section. Overall it's a great website, hope you get your approved soon :)

**Comment by patriciachrysy** [comment]
Good job @nyatindopatrick !!! I just have three remarks for you:
- same remark as Kyle
- Check the reset filter button, the text is going out of the bounds
- Check the original design again for elements dispositions before you submit for review

**Comment by nyatindopatrick** [comment]
Thank you all for the reviews.
